compressionLevel: 9

enableColors: false

enableGlobalCache: false

enableTelemetry: false

#nmHoistingLimits: workspaces

nmMode: hardlinks-local

nodeLinker: node-modules

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.2.cjs
